import Head from 'next/head'
import Topo from '@/src/componentes/Topo'

import Linha2 from '@/src/componentes/Linha2'
import Linha3 from '@/src/componentes/Linha3'
import Produtos from '@/src/componentes/Produtos'
import Linha5 from '@/src/componentes/Linha5'
import Linha6 from '@/src/componentes/Linha6'
import Final from '@/src/componentes/Final'

export default function Home() {
  return (
    <>
      <Head>
        <title>Curadoria Nacional</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&family=Roboto+Mono&family=Roboto:wght@500;700&display=swap" rel="stylesheet"/>
      </Head>
      
  <div>

    <Topo />
    <Linha2 />
    <Linha3 />
    <Produtos />
    <Linha5 />
    <Linha6 />
    <Final />

</div>
    </>
  )
}
